# Numpy Project - Part 2: The Validity of a solution

We'll reveal the true objective of this project: create an algorithm to solve sudokus! That'll be a ton of fun, but for now, we need to first nail down a few required functions.

For this second part, we'll be trying to validate a board; if a proposed solution is valid or not. As you might know, the rules of Sudoku are straightforward: there are numbers 1-9 and they can't be repeated in either rows, columns or 3x3 blocks.

**IMPORTANT:** This 2nd part will use the `Board` class produced in Part 1. Make sure all the tests are passing.

In [1]:
import numpy as np
import collections

from sudoku import Board

In this case, we'll use the following two sudoku boards. Our original one from part 1:

<img src="https://user-images.githubusercontent.com/872296/68136001-49d21400-ff03-11e9-8750-acb846e23046.png" width="600px">

In [2]:
arr_valid = np.array([
    [0, 2, 0, 0, 8, 0, 0, 5, 0],
    [4, 0, 0, 0, 0, 6, 8, 0, 0],
    [6, 0, 0, 4, 5, 3, 9, 7, 0],
    [0, 0, 0, 0, 0, 2, 0, 9, 0],
    [0, 0, 4, 0, 0, 0, 6, 0, 0],
    [0, 1, 0, 3, 0, 0, 0, 0, 0],
    [0, 5, 7, 1, 3, 4, 0, 0, 9],
    [0, 0, 9, 6, 0, 0, 0, 0, 5],
    [0, 3, 0, 0, 2, 0, 0, 8, 0]])

and an "invalid" one, that we've purposely invalidated to practice these functions. We've introduced 3 numbers that invalidate sudoku rules (marked in red):

<img src="https://user-images.githubusercontent.com/872296/68214887-05a34a00-ffbd-11e9-9f6f-922b69599428.png" width="600px" align="center">

The number `5` added in the 2nd row, 2nd column invalidates the board because there's another number `5` in the same column. The number `8` invalidates as there's another `8` in the same block, and `4` is repeated in the same row.

In [3]:
arr_invalid = np.array([
    [0, 2, 0, 0, 8, 0, 0, 5, 0],
    [4, 5, 0, 0, 8, 6, 8, 0, 0],
    [6, 0, 0, 4, 5, 3, 9, 7, 0],
    [0, 0, 0, 0, 0, 2, 0, 9, 0],
    [0, 0, 4, 0, 0, 0, 6, 4, 0],
    [0, 1, 0, 3, 0, 0, 0, 0, 0],
    [0, 5, 7, 1, 3, 4, 0, 0, 9],
    [0, 0, 9, 6, 0, 0, 0, 0, 5],
    [0, 3, 0, 0, 2, 0, 0, 8, 0]])

Initializing now the boards objects:

In [42]:
valid = Board(arr_valid)
invalid = Board(arr_invalid)
valid.arr

array([[0, 2, 0, 0, 8, 0, 0, 5, 0],
       [4, 0, 0, 0, 0, 6, 8, 0, 0],
       [6, 0, 0, 4, 5, 3, 9, 7, 0],
       [0, 0, 0, 0, 0, 2, 0, 9, 0],
       [0, 0, 4, 0, 0, 0, 6, 0, 0],
       [0, 1, 0, 3, 0, 0, 0, 0, 0],
       [0, 5, 7, 1, 3, 4, 0, 0, 9],
       [0, 0, 9, 6, 0, 0, 0, 0, 5],
       [0, 3, 0, 0, 2, 0, 0, 8, 0]])

### Testing if a row, column or block is valid

We'll write a function `is_subset_valid` that will receive either a row, column or block, and return if it's valid or not.

##### a) Checking rows

In [41]:
def is_subset_valid(arr):
    arr_new = arr[arr > 0]
    #print(arr_new)
    if arr_new.size == 0:
        return True
    for i in range(0,arr_new.size):
        for j in range(i+1,arr_new.size):
            #print(arr_new[i])
            #print(arr_new[j])
            if arr_new[i] == arr_new[j]:
                return False
    return True

is_subset_valid(invalid_block)

False

Let's test it with different things:

In [25]:
valid_row = valid.get_row(1)
valid_row

array([4, 0, 0, 0, 0, 6, 8, 0, 0])

In [26]:
assert is_subset_valid(valid_row) is True

In [27]:
invalid_row = invalid.get_row(4)
invalid_row  # Number 4 is repeated

array([0, 0, 4, 0, 0, 0, 6, 4, 0])

In [28]:
assert is_subset_valid(invalid_row) is False

##### a) Checking columns

In [30]:
valid_col = valid.get_column(3)
valid_col
is_subset_valid(valid_col)

True

In [31]:
assert is_subset_valid(valid_col) is True

In [33]:
invalid_col = invalid.get_column(1)
invalid_col  # Number 5 is repeated
is_subset_valid(invalid_col)

False

In [34]:
assert is_subset_valid(invalid_col) is False

##### a) Checking blocks

In [35]:
valid_block = valid.get_block(0, 1)
valid_block

array([[0, 8, 0],
       [0, 0, 6],
       [4, 5, 3]])

In [38]:
assert is_subset_valid(valid_block) is True

[8 6 4 5 3]


In [39]:
invalid_block = invalid.get_block(0, 1)
invalid_block  # Number 8 is repeated

array([[0, 8, 0],
       [0, 8, 6],
       [4, 5, 3]])

In [40]:
assert is_subset_valid(invalid_block) is False

[8 8 6 4 5 3]


### Testing a valid board

We can now move forward to our `is_valid` function, that will receive a `Board` and will check if it's valid or not.

In [62]:
def is_valid(board):
    for i in range(0,9):
        row = board.get_row(i)
        col = board.get_column(i)
        if ((is_subset_valid(row) == False) | (is_subset_valid(col) == False)):
            return False
    for i in range(0,3):
        for j in range(0,3):
            block = board.get_block(i,j)
            if is_subset_valid(block) == False:
                return False
    return True

is_valid(invalid)

False

And now we can test it:

In [63]:
assert is_valid(valid) is True

In [64]:
assert is_valid(invalid) is False

## Time to test!

Now it's time to move your code to `sudoku.py` and then run all the tests; if they're passing, you can move to the next step!

In [65]:
!py.test test_part_2.py

============================= test session starts ==============================
platform darwin -- Python 3.6.10, pytest-5.2.2, py-1.8.1, pluggy-0.13.1
rootdir: /Users/neha/DS Projects/RMOTR Projects/NPY-sudoku-solver-numpy-master
collected 8 items                                                              

test_part_2.py ........                                                  [100%]

============================== 8 passed in 0.80s ===============================
