# Numpy Project - Part 3: Other helper functions

In our quest to find the final solution for our sudoku, we'll finish writing a few important functions that will make the solving algorithm a lot simpler. It might not make a ton of sense now, but hopefully it'll be clear once we get to the point of finding the solution.

In [22]:
import numpy as np
from sudoku import Board

As we've done so far, this is the sudoku we're working with:

<img src="https://user-images.githubusercontent.com/872296/68136001-49d21400-ff03-11e9-8750-acb846e23046.png" width="600px">

In [23]:
puzzle = Board(np.array([
    [0, 2, 0, 0, 8, 0, 0, 5, 0],
    [4, 0, 0, 0, 0, 6, 8, 0, 0],
    [6, 0, 0, 4, 5, 3, 9, 7, 0],
    [0, 0, 0, 0, 0, 2, 0, 9, 0],
    [0, 0, 4, 0, 0, 0, 6, 0, 0],
    [0, 1, 0, 3, 0, 0, 0, 0, 0],
    [0, 5, 7, 1, 3, 4, 0, 0, 9],
    [0, 0, 9, 6, 0, 0, 0, 0, 5],
    [0, 3, 0, 0, 2, 0, 0, 8, 0]]))

### 1) Find empty squares

First we are going to need a function that will tell us where the empty squares are within our board. 

We'll write a function `find_empty` that receives a game board instance and returns the position of all the empty cells in the board.

If there are no empty cells on the board, the function will return `None`.

In [24]:
def find_empty(board):
    arr = board.arr
    if((arr == 0).all()):
        return None
    lst = []
    for i in range(0,9):
        for j in range(0,9):
            if arr[i, j] == 0:
                lst.append(np.array([i,j]))
    return np.array(lst)

find_empty(puzzle)

array([[0, 0],
       [0, 2],
       [0, 3],
       [0, 5],
       [0, 6],
       [0, 8],
       [1, 1],
       [1, 2],
       [1, 3],
       [1, 4],
       [1, 7],
       [1, 8],
       [2, 1],
       [2, 2],
       [2, 8],
       [3, 0],
       [3, 1],
       [3, 2],
       [3, 3],
       [3, 4],
       [3, 6],
       [3, 8],
       [4, 0],
       [4, 1],
       [4, 3],
       [4, 4],
       [4, 5],
       [4, 7],
       [4, 8],
       [5, 0],
       [5, 2],
       [5, 4],
       [5, 5],
       [5, 6],
       [5, 7],
       [5, 8],
       [6, 0],
       [6, 6],
       [6, 7],
       [7, 0],
       [7, 1],
       [7, 4],
       [7, 5],
       [7, 6],
       [7, 7],
       [8, 0],
       [8, 2],
       [8, 3],
       [8, 5],
       [8, 6],
       [8, 8]])

For example, the first empty positions should look like:

In [25]:
find_empty(puzzle)[:5, :5]

array([[0, 0],
       [0, 2],
       [0, 3],
       [0, 5],
       [0, 6]])

In [26]:
assert np.array_equal(find_empty(puzzle)[:7, :7], np.array([
    [0, 0],
    [0, 2],
    [0, 3],
    [0, 5],
    [0, 6],
    [0, 8],
    [1, 1]]))

### 2) Is full

This function just returns `True` if all the cells are full. `False` if there are any `0s`.

In [27]:
def is_full(board):
    arr = board.arr
    if (arr == 0).any():
        return False
    else:
        return True

In [28]:
assert is_full(puzzle) is False

In [61]:
temp = puzzle.arr

row = puzzle.get_row(7)
col = puzzle.get_column(7)

def block_pos(cellno):
    if cellno <3:
        return 0
    elif 3<=cellno<6:
        return 1
    else:
        return 2

pos_1 = block_pos(7)
pos_2 = block_pos(7)
bo = puzzle.get_block(pos_1,pos_2)
print(np.sort(row))
print(np.sort(col))
print(pos_1, pos_2)

for x in range(1,10):
    if (x not in row) & (x not in col) & (x not in bo.flatten()):
        print(x)

[0 0 0 0 0 0 5 6 9]
[0 0 0 0 0 5 7 8 9]
2 2
1
2
3
4


### 3) Find possibilities

We need to write now a function that will find, for a given cell, all the possible values. For example, for the cell in position `2, 1` the only possible value is `8`, try it yourself:

![sudoku-pos1](https://user-images.githubusercontent.com/872296/68609582-70102a80-0494-11ea-8335-95373f66563f.png)

For `2, 2`, the only possible values are `1` and `8`. Complete the function `find_possibilities` that receives a `Board` and the position of a cell and returns all the valid possible values for that cell:

In [76]:
def find_possibilities(board, x, y):
    arr = board.arr
    print(arr)
    row = board.get_row(x)
    row_vals = row[row>0]
    print(row_vals)
    
    col = board.get_column(y)
    col_vals = col[col>0]
    print(col_vals)
    
    pos_1 = block_pos(x)
    pos_2 = block_pos(y)
    block = board.get_block(pos_1,pos_2)
    clean_block = block[block>0]
    print(pos_1, pos_2)
    print(clean_block)
    possible_nos = [i for i in range(1,10) if (i not in row_vals) & (i not in col_vals) & (i not in clean_block)] 
    return np.array(possible_nos)

def block_pos(cellno):
    if cellno <3:
        return 0
    elif 3<=cellno<6:
        return 1
    else:
        return 2

find_possibilities(puzzle,2,1)

[[0 2 0 0 8 0 0 5 0]
 [4 0 0 0 0 6 8 0 0]
 [6 0 0 4 5 3 9 7 0]
 [0 0 0 0 0 2 0 9 0]
 [0 0 4 0 0 0 6 0 0]
 [0 1 0 3 0 0 0 0 0]
 [0 5 7 1 3 4 0 0 9]
 [0 0 9 6 0 0 0 0 5]
 [0 3 0 0 2 0 0 8 0]]
[6 4 5 3 9 7]
[2 1 5 3]
0 0
[2 4 6]


array([8])

In [71]:
assert set(find_possibilities(puzzle, 2, 1)) == set(np.array([8]))

[[0 2 0 0 8 0 0 5 0]
 [4 0 0 0 0 6 8 0 0]
 [6 0 0 4 5 3 9 7 0]
 [0 0 0 0 0 2 0 9 0]
 [0 0 4 0 0 0 6 0 0]
 [0 1 0 3 0 0 0 0 0]
 [0 5 7 1 3 4 0 0 9]
 [0 0 9 6 0 0 0 0 5]
 [0 3 0 0 2 0 0 8 0]]
[6 4 5 3 9 7]
[2 1 5 3]
0 0
[[0 2 0]
 [4 0 0]
 [6 0 0]]


In [72]:
assert set(find_possibilities(puzzle, 2, 2)) == set(np.array([1, 8]))

[[0 2 0 0 8 0 0 5 0]
 [4 0 0 0 0 6 8 0 0]
 [6 0 0 4 5 3 9 7 0]
 [0 0 0 0 0 2 0 9 0]
 [0 0 4 0 0 0 6 0 0]
 [0 1 0 3 0 0 0 0 0]
 [0 5 7 1 3 4 0 0 9]
 [0 0 9 6 0 0 0 0 5]
 [0 3 0 0 2 0 0 8 0]]
[6 4 5 3 9 7]
[4 7 9]
0 0
[[0 2 0]
 [4 0 0]
 [6 0 0]]


In [73]:
assert set(find_possibilities(puzzle, 0, 0)) == set(np.array([1, 3, 7 ,9]))

[[0 2 0 0 8 0 0 5 0]
 [4 0 0 0 0 6 8 0 0]
 [6 0 0 4 5 3 9 7 0]
 [0 0 0 0 0 2 0 9 0]
 [0 0 4 0 0 0 6 0 0]
 [0 1 0 3 0 0 0 0 0]
 [0 5 7 1 3 4 0 0 9]
 [0 0 9 6 0 0 0 0 5]
 [0 3 0 0 2 0 0 8 0]]
[2 8 5]
[4 6]
0 0
[[0 2 0]
 [4 0 0]
 [6 0 0]]


## Time to test!

Now it's time to move your code to `sudoku.py` and then run all the tests; if they're passing, you can move to the next step!

In [77]:
!py.test test_part_3.py

============================= test session starts ==============================
platform darwin -- Python 3.6.10, pytest-5.2.2, py-1.8.1, pluggy-0.13.1
rootdir: /Users/neha/DS Projects/RMOTR Projects/NPY-sudoku-solver-numpy-master
collected 3 items                                                              

test_part_3.py ...                                                       [100%]

============================== 3 passed in 0.75s ===============================
